name: Release Packages

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  release:
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - icons-material
          - icons-ant
    defaults:
      run:
        working-directory: packages/${{ matrix.package }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm i

      - name: Publish package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SVGD_NPM_TOKEN }}
